project_id = "xmmyjphoaqazwlifehxs"

[functions.create-zoho-lead]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.convert-zoho-lead-to-contact]
verify_jwt = false