project_id = "xmmyjphoaqazwlifehxs"

[functions.create-zoho-contact]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.update-zoho-contact-user-type]
verify_jwt = false

[functions.update-zoho-contact-referral]
verify_jwt = false
