headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
edge_functions = "/Users/skoly/code/vinca-wealth/vinca-product-v2/netlify/edge-functions"
publish = "/Users/skoly/code/vinca-wealth/vinca-product-v2/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]
skip_processing = false

[build.processing.css]

[build.processing.html]
pretty_urls = true

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
function = "og-tags"
path = "/blog/*"

[functions]

[functions."*"]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]